#!/usr/bin/env python3
"""
FORGE model registry builder — makes routing self-adjusting.

Produces ~/.claude/forge-models.json, the data the swarm routes by. The
workflow NEVER hardcodes model IDs; it reads this registry via args.models.

How it auto-adjusts (first-principles, MECE):
  1. WITHIN-FAMILY upgrades (Opus 5.1, Fable 6, Haiku 5): the registry uses
     floating FAMILY ALIASES ('opus','sonnet','haiku','fable'), which the Claude
     Code harness resolves to the CURRENT model of that family. Nothing to do.
  2. STRUCTURAL changes (a family appears/disappears, ladder re-orders): this
     script re-derives the ladder + tiers from whatever families are available,
     by matching model IDs to families by SUBSTRING and picking the newest
     version — so 'claude-opus-5-1' and 'claude-fable-6' classify correctly
     without any code edit.
  3. DISCOVERY: if ANTHROPIC_API_KEY is set, it lists live models from the API;
     otherwise it assumes the known families (which the harness supports).

Usage:
  python3 forge-models.py            # write ~/.claude/forge-models.json
  python3 forge-models.py --print    # print registry to stdout, don't write
  python3 forge-models.py --selftest # prove future models classify correctly
"""
import json
import os
import re
import sys

HOME = os.path.expanduser("~")
OUT = os.path.join(HOME, ".claude", "forge-models.json")

# Canonical capability order, weakest -> strongest. New FAMILIES (not versions)
# would be added here; new VERSIONS of these need no change (aliases float).
CANON = ["haiku", "sonnet", "opus", "fable"]


def _version_key(model_id: str):
    """Numeric version tuple from an id like 'claude-opus-5-1' -> (5, 1)."""
    nums = re.findall(r"\d+", model_id)
    return tuple(int(n) for n in nums) if nums else (0,)


def classify_families(model_ids):
    """Bucket ids by family substring; keep the newest version per family.
    Robust to future versions: 'claude-opus-5-1' matches family 'opus'."""
    best = {}
    for mid in model_ids:
        low = mid.lower()
        for fam in CANON:
            if fam in low:
                if fam not in best or _version_key(mid) > _version_key(best[fam]):
                    best[fam] = mid
                break
    return best


def build_registry(present_families, resolved=None):
    """Derive the routing registry from the families that exist, in canon order.
    Values are ALIASES (float to latest). Degrades gracefully if some families
    are missing."""
    ladder = [f for f in CANON if f in present_families]
    if not ladder:
        ladder = list(CANON)  # nothing discovered → assume the known set
    strongest = ladder[-1]
    hard = ladder[-2] if len(ladder) >= 2 else ladder[-1]
    medium = ladder[1] if len(ladder) >= 3 else hard
    weakest = ladder[0]
    reg = {
        "_comment": "Auto-generated by forge-models.py. Values are floating family aliases. "
                    "Edit to pin versions, re-order the ladder, or add a new family — no code change needed.",
        "ladder": ladder,
        "tiers": {"trivial": weakest, "light": weakest, "medium": medium, "hard": hard},
        "mind": strongest,
        "planCritic": hard,
        "aggregator": strongest,
        "voter": medium,
        "ensemble": [m for m in (hard, medium, strongest)] if len(ladder) >= 3 else ladder,
    }
    if resolved:
        reg["_resolvedToLatestIds"] = resolved  # reference only; routing still uses aliases
    return reg


def discover_model_ids():
    """Best-effort live list. Falls back to the known families as pseudo-ids."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if key:
        try:
            import urllib.request
            req = urllib.request.Request(
                "https://api.anthropic.com/v1/models",
                headers={"x-api-key": key, "anthropic-version": "2023-06-01"},
            )
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.load(r)
            ids = [m.get("id", "") for m in data.get("data", [])]
            if ids:
                return ids
        except Exception:
            pass
    # No API access → assume the harness-supported families (aliases float anyway).
    return list(CANON)


def selftest():
    ok = 0
    fail = 0

    def chk(name, cond):
        nonlocal ok, fail
        print(("  PASS " if cond else "  FAIL ") + name)
        ok += cond
        fail += (not cond)

    # Today's models classify to the canonical registry.
    today = ["claude-haiku-4-5-20251001", "claude-sonnet-5", "claude-opus-4-8", "claude-fable-5"]
    fam = classify_families(today)
    reg = build_registry(list(fam.keys()), fam)
    print("TEST A — today's models → canonical registry")
    chk("hard=opus", reg["tiers"]["hard"] == "opus")
    chk("medium=sonnet", reg["tiers"]["medium"] == "sonnet")
    chk("mind=fable", reg["mind"] == "fable")
    chk("ensemble = opus+sonnet+fable", reg["ensemble"] == ["opus", "sonnet", "fable"])

    # THE KEY TEST: future models auto-classify with NO code change.
    future = ["claude-haiku-5", "claude-sonnet-6", "claude-opus-5-1", "claude-fable-6"]
    famf = classify_families(future)
    print("TEST B — future models (Opus 5.1, Fable 6, Haiku 5, Sonnet 6) auto-classify")
    chk("opus resolves to 5-1", famf["opus"] == "claude-opus-5-1")
    chk("fable resolves to 6", famf["fable"] == "claude-fable-6")
    chk("versioned picks newest", _version_key("claude-opus-5-1") > _version_key("claude-opus-4-8"))

    # Mixed old+new versions of the same family → newest wins.
    mixed = ["claude-opus-4-8", "claude-opus-5-1", "claude-opus-5-0"]
    chk("newest opus among mixed", classify_families(mixed)["opus"] == "claude-opus-5-1")

    # Structural: a family missing → ladder + tiers degrade sensibly.
    three = classify_families(["claude-haiku-4-5", "claude-sonnet-5", "claude-opus-4-8"])
    reg3 = build_registry(list(three.keys()))
    print("TEST C — a family missing (no fable) → graceful degrade")
    chk("ladder has 3", reg3["ladder"] == ["haiku", "sonnet", "opus"])
    chk("mind falls back to opus", reg3["mind"] == "opus")

    print(f"\n{'ALL GREEN' if fail == 0 else 'FAILURES'} — {ok} passed, {fail} failed")
    return 0 if fail == 0 else 1


def main():
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    ids = discover_model_ids()
    fam = classify_families(ids)
    resolved = fam if any(f != fam.get(f) for f in fam) else None
    reg = build_registry(list(fam.keys()), resolved)
    if "--print" in sys.argv:
        print(json.dumps(reg, indent=2))
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(reg, f, indent=2)
    print(f"Wrote {OUT}")
    print(json.dumps(reg, indent=2))


if __name__ == "__main__":
    main()
